Add epd7in5b_v2 support
caemor/epd-waveshare pull request #118
Opened 2022-10-14 10:59 UTC by peckpeck

Support of 7.5" (b) v2 (3 colors with back, white, red)
It is based on  epd7in5_v2 which doesn't work (epd7in5_v3 neither)
It is also based on the arduino C driver and datasheet.
It works on my V3 but the C driver and the datasheet haven't changed between v2 and v3.

2022-10-20 18:27 UTC, caemor commented on src/epd7in5b_v2/command.rs
> +//! SPI Commands for the Waveshare 7.5"(B) V2 E-Ink Display
```suggestion
//! SPI Commands for the Waveshare 7.5"(B) V2 and V3 E-Ink Display
```

Maybe include the v3 as well then if its already tested and working with the same commands.

2022-10-20 19:04 UTC, caemor requested changes
Could you please add the display(s) to the changelog and the readme as well?

2022-10-21 14:12 UTC, peckpeck commented
Done

2022-10-21 15:53 UTC, caemor approved these changes
Thanks

2022-10-21 15:54 UTC, merged