Add the heap allocation feature
caemor/epd-waveshare pull request #127
Opened 2022-11-22 20:40 UTC by mangelajo

Some platforms (like ESP32) have a limited stack size, but a bigger heap which can range 2-4MBytes for spiram. In such platforms it's impossible to allocate most of the displays in the stack, but it's possible to get them heap allocated (as long as we are compiling with std).

This commit adds the "heap" feature, disabled by default, which will import std, and add the ability to create the display graphics in heap instead of the stack.

2022-11-22 20:54 UTC, mangelajo commented
ha, fmt is very unhappy, fixing that.

2022-11-22 21:07 UTC, mangelajo commented
I am hearing suggestions on the esp-rs matrix:

* allow passing down a buffer instead to the display, i.e. :
```
#[link_section = ".ext_ram.bss.frame_buffer"]
static FRAME_BUFFER: StaticCell<[u8; N]> = StaticCell::new();

``` 

* using alloc instead of std::Box
```
extern crate alloc;
use alloc::boxed::Box;
```

2022-11-22 21:24 UTC, mangelajo commented
ha... last minute changes... it doesn't work now:

``` 
error[E0599]: no function or associated item named `new` found for struct `epd_waveshare::epd5in65f::Display5in65f` in the current scope
   --> src/peripherals/display.rs:155:66
    |
155 |             let mut display: Box<Display5in65f> = Display5in65f::new();
    |                                                                  ^^^ function or associated item not found in `epd_waveshare::epd5in65f::Display5in65f`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use epd_waveshare::traits::HeapAllocated;
```

2022-11-23 20:20 UTC, peckpeck commented
If you look at https://github.com/caemor/epd-waveshare/pull/123 you can see that the `Default` display is `#[inline(always)]` which means that you can skip the stack allocation of a display by just doing `Box::new(DisplayXX::default())`

2022-11-28 21:48 UTC, mangelajo commented
> If you look at #123 you can see that the `Default` display is `#[inline(always)]` which means that you can skip the stack allocation of a display by just doing `Box::new(DisplayXX::default())`
> 
> Without needing `std` in the library :-)

Oh awesome, I like your approach much better then. I will give a try to your PR and report back :)

2022-11-28 21:58 UTC, caemor commented
I finally hat time to merge Peckpecks PR, so if his idea already resolves your issue, we could change this pr/make a different one where we add it to the readme as an faq point or similar.

2022-11-29 20:35 UTC, mangelajo commented
I will do that @caemor !

2022-12-07 21:10 UTC, mangelajo commented
Oh sorry, right it was on me to document this.

2022-12-08 14:26 UTC, mangelajo commented
Ok, I converted it to documentation.

2022-12-08 18:09 UTC, caemor requested changes

2022-12-08 18:09 UTC, caemor commented on src/traits.rs
> +///epd.display_frame(&mut spi, &mut delay)?;
```suggestion
```

just remove these lines, since they bring no immediate benefit here

2022-12-08 18:09 UTC, caemor commented on src/traits.rs
> +///```rust, no_run
```suggestion
///```rust, no_run
///# use epd_waveshare::epd4in2::Display4in2;
///# use embedded_graphics_core::prelude::*;
```

2022-12-08 18:09 UTC, caemor commented on src/traits.rs
> +///```rust, no_run
We need to add the necessary includes

2022-12-08 18:23 UTC, caemor commented on src/traits.rs
> +///epd.display_frame(&mut spi, &mut delay)?;
If you use `cargo test` before commiting it should show you the necessary parts to fix as well.

2023-09-28 13:51 UTC, caemor submitted a review, later dismissed

2024-11-04 10:27 UTC, merged