Add 7in5bc support, #26
caemor/epd-waveshare pull request #45
Opened 2020-04-14 08:32 UTC by marcelbuesing

I'm working on 7in5bc support for aer and since I wanted to try out the colors I added the 7in5bc version. It's mostly copy and paste besides docs and the `fn update_color_frame`. It looks like this is a little different to e.g. the 2in9bc where the update of chromatic and monochromatic part appears to happen separately. 
I still added `update_achromatic_frame` and `update_chromatic_frame` but it adds little value since it's not possible to set e.g. the chromatic part first and then only update the achromatic part (haven't tested if it works the other way around).

![image](https://user-images.githubusercontent.com/5637837/79202817-6ff8ca00-7e3a-11ea-86f9-82256acb16be.png)

2020-05-13 09:26 UTC, caemor commented
> I still added update_achromatic_frame and update_chromatic_frame but it adds little value since it's not possible to set e.g. the chromatic part first and then only update the achromatic part (haven't tested if it works the other way around).

Could you please add this to the documentation of this display and to the these two functions. 
This might be useful for people with smaller RAMs to first update the achromatic and then reuse the same buffer for the chromatic part.

Everything else looks really good

2021-01-27 20:46 UTC, caemor requested changes
See last message and could you maybe rebase this to main?

2021-03-03 20:06 UTC, marcelbuesing commented on src/epd7in5bc/mod.rs
> +        self.interface.reset(delay, 10);
Assuming 10 is fine here but I can not verify this due to missing display.

2021-03-03 20:06 UTC, marcelbuesing commented
> See last message and could you maybe rebase this to main?

Sorry my 7in5c display died some time last year when I accidentally dropped it and it did not make sense to order the v1 version again. I rebased the branch but it would be good to try the chromatic/achromatic fns as maybe I just tried it the wrong way around last year.

2022-08-01 06:52 UTC, merged