Provide full QuickRefresh interface for 4.2 inch display
caemor/epd-waveshare pull request #81
Opened 2021-07-14 21:25 UTC by sirhcel

The Waveshare 4.2 inch display needs no special commands for displaying the new frame. But it will come in handy to support the full `QuickRefresh` trait when it comes to supporting different quick refresh capable displays from an application.

This PR implements `display_new_frame` and `update_and_display_new_frame` using the already existing methods. It also brings some cleanup to warnings from `cargo doc` which showed up when checking the docs for the newly implemented methods.

2021-07-14 21:27 UTC, sirhcel commented
And once again I forgot to say a big thank you for providing and maintaining this crate! :)

2021-07-15 05:53 UTC, caemor requested changes
Thanks for your PR.

2021-07-15 05:53 UTC, caemor commented on src/epd4in2/mod.rs
> +    /// This is wrapper around `display_frame` for using this device as a true
```suggestion
    /// This is a wrapper around `display_frame` for using this device as a true
```

2021-07-15 05:55 UTC, caemor approved these changes

2021-07-15 05:56 UTC, caemor commented
The improvements to the docs and the 4in2 display looks good to me so I will go forward and merge this already.

2021-07-15 05:57 UTC, merged